dist: trusty
language: java
addons:
  apt:
    packages:
      - openjdk-7-jdk
jdk:
  - openjdk7
install:
  - mvn install -DskipTests=true -B -V
script:
  - mvn verify -B
after_success:
  - "[[ ${TRAVIS_PULL_REQUEST} == 'false' ]] && [[ ${TRAVIS_TAG} == '' ]] && mvn deploy -DskipTests"
